In [1]:
include("SkyrmeParams.jl")
using .LambdaParameters
function testgetaΛ()
    LambdaParameters.getaΛ("HPΛ1")
    #getaΛ("HPΛ1") #usingの有無に関わらす　not defined
end

testgetaΛ()

4-element Vector{Float64}:
 -290.00195749999995
   16.010749999999998
   28.308124999999997
  527.4135095624999

In [2]:
include("SkyrmeParams.jl")
using .NuclParameters
function testgetaN()
    NuclParameters.getaN("SLy4")
end

testgetaN()

10-element Vector{Float64}:
 -1763.392735
  1660.10297
  1554.5048333333334
 -2128.5465
    32.47299000000001
    49.31277
    92.6534925
   -31.314172500000005
   -23.682745
    64.575625

In [6]:
include("Main.jl")
function testh2m()
    TestNum=10
    ρN=1:TestNum
    ρq=1:TestNum
    ρΛ=1:TestNum
    aΛ=LambdaParameters.getaΛ("HPΛ1")
    aN=NuclParameters.getaN("SLy4")
    ansΛ=h2mΛ(aΛ,ρN/aΛ[2])
    ansN=h2mN(1,aN,ρN/aN[5],ρq/aN[6],aΛ,ρΛ/aΛ[2])
    println("ansΛ=")
    show(ansΛ)
    println("")
    println("ansN=")
    show(ansN)
    
end
testh2m()

ansΛ=
[18.450269114874917, 19.450269114874917, 20.450269114874917, 21.450269114874917, 22.450269114874917, 23.450269114874917, 24.450269114874917, 25.450269114874917, 26.450269114874917, 27.450269114874917]
ansN=
[23.721248539064334, 26.721248539064334, 29.721248539064334, 32.721248539064334, 35.721248539064334, 38.721248539064334, 41.721248539064334, 44.721248539064334, 47.721248539064334, 50.721248539064334]

In [17]:
ρ1=ones(Float64,10,10)
Ones=ones(Float64,10)
for i in 1:10
    @. ρ1[:,i]=i*Ones[:]
end
ρ1

10×10 Matrix{Float64}:
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0

In [12]:
include("Main.jl")
SPS=SingleParticleState[]
println(typeof(SPS))

Vector{SingleParticleState}


In [11]:
function TestArray()
    A=[Float64[],Float64[],Float64[]]
    for i in 1:10
        push!(A[1],0.1*i)
        push!(A[2],1*i)
        push!(A[3],10*i)
    end
    return A
end
A=TestArray()
A[1][3]

0.30000000000000004

In [15]:
A=[[1],[1,2],[1,2,3]]
eachindex(A[1][])

Base.OneTo(1)

In [4]:
typeof(sign(-1))

Int64

In [4]:
mkdir("my/path")

Base.IOError: IOError: mkdir("my/path"; mode=0o777): file already exists (EEXIST)