In [1]:
include("SkyrmeParams.jl")
using .LambdaParameters
function testgetaΛ()
    LambdaParameters.getaΛ("HPΛ1")
    #getaΛ("HPΛ1") #usingの有無に関わらす　not defined
end

testgetaΛ()

4-element Vector{Float64}:
 -290.00195749999995
   16.010749999999998
   28.308124999999997
  527.4135095624999

In [2]:
include("SkyrmeParams.jl")
using .NuclParameters
function testgetaN()
    NuclParameters.getaN("SLy4")
end

testgetaN()

10-element Vector{Float64}:
 -1763.392735
  1660.10297
  1554.5048333333334
 -2128.5465
    32.47299000000001
    49.31277
    92.6534925
   -31.314172500000005
   -23.682745
    64.575625

In [6]:
include("Main.jl")
function testh2m()
    TestNum=10
    ρN=1:TestNum
    ρq=1:TestNum
    ρΛ=1:TestNum
    aΛ=LambdaParameters.getaΛ("HPΛ1")
    aN=NuclParameters.getaN("SLy4")
    ansΛ=h2mΛ(aΛ,ρN/aΛ[2])
    ansN=h2mN(1,aN,ρN/aN[5],ρq/aN[6],aΛ,ρΛ/aΛ[2])
    println("ansΛ=")
    show(ansΛ)
    println("")
    println("ansN=")
    show(ansN)
    
end
testh2m()

ansΛ=
[18.450269114874917, 19.450269114874917, 20.450269114874917, 21.450269114874917, 22.450269114874917, 23.450269114874917, 24.450269114874917, 25.450269114874917, 26.450269114874917, 27.450269114874917]
ansN=
[23.721248539064334, 26.721248539064334, 29.721248539064334, 32.721248539064334, 35.721248539064334, 38.721248539064334, 41.721248539064334, 44.721248539064334, 47.721248539064334, 50.721248539064334]

In [17]:
ρ1=ones(Float64,10,10)
Ones=ones(Float64,10)
for i in 1:10
    @. ρ1[:,i]=i*Ones[:]
end
ρ1

10×10 Matrix{Float64}:
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0

In [12]:
include("Main.jl")
SPS=SingleParticleState[]
println(typeof(SPS))

Vector{SingleParticleState}


In [11]:
function TestArray()
    A=[Float64[],Float64[],Float64[]]
    for i in 1:10
        push!(A[1],0.1*i)
        push!(A[2],1*i)
        push!(A[3],10*i)
    end
    return A
end
A=TestArray()
A[1][3]

0.30000000000000004

In [15]:
A=[[1],[1,2],[1,2,3]]
eachindex(A[1][])

Base.OneTo(1)

In [4]:
typeof(sign(-1))

Int64

In [4]:
mkdir("my/path")

Base.IOError: IOError: mkdir("my/path"; mode=0o777): file already exists (EEXIST)

In [1]:
io=open("hoge.txt","w")
typeof(io)

IOStream

In [4]:
AN=[
		[6,5],
		[8,7],
		[14,13],
		[23,27],
		[39,49],
		[52,81],
		[82,125]
	]
for i=eachindex(AN)
    println(AN[i][1] ,AN[i][2])
end

65
87
1413
2327
3949
5281
82125


In [4]:
using CSV, DataFrames
df=DataFrame(CSV.File("Lambda Parameters.csv"))

35×30 DataFrame
 Row │ index  Parameter Name                     Paper          a1           a ⋯
     │ Int64  String                             String15       Float64      F ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │     1  YBZ1                               Yamamoto1988   -330.154     2 ⋯
   2 │     2  YBZ2                               Yamamoto1988   -375.149     2
   3 │     3  YBZ3                               Yamamoto1988   -237.004     2
   4 │     4  YBZ4                               Yamamoto1988   -224.981     2
   5 │     5  YBZ5                               Yamamoto1988   -298.116       ⋯
   6 │     6  YBZ6                               Yamamoto1988   -352.287     4
   7 │     7  SKSH1                              Fernandez1989  -176.5
   8 │     8  SKSH2                              Fernandez1989  -290.0
  ⋮  │   ⋮                    ⋮                        ⋮             ⋮         ⋱
  29 │    29  GKW2+MD1_medium                    my parameter     -0.904726  3 ⋯
  30 │    30  GKW3+MD2_medium                    my parameter    -90.8192    3
  31 │    31  GKW3+MD3_medium                    my parameter     -1.05162   4
  32 │    32  GKW2_medium(rho<1.5)               my parameter   -352.208
  33 │    33  GKW3_medium(rho<1.5)               my parameter   -388.277       ⋯
  34 │    34  GKW2_medium(rho<1.5)+Kohno2(k<1.…  my parameter   -352.208     4
  35 │    35  GKW3_medium(rho<1.5)+Kohno3(k<1.…  my parameter   -388.277     5
                                                  26 columns and 20 rows omitted

In [5]:
df[!,"y34"]

35-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0